services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      - "DatabaseSettings__ConnectionString=Host=db;Database=db;\
        Username=sa;Password=SuperSecurePassword123!;Include Error Detail=true"
      - "DatabaseSettings__DBProvider=postgresql"
      - "HangfireSettings__Storage__ConnectionString=Host=db;Database=db;\
        Username=sa;Password=SuperSecurePassword123!;Include Error Detail=true"
      - "HangfireSettings__Storage__StorageProvider=postgresql"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=SuperSecurePasswor\
        d123!"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5050:5050"
      - "5060:5060"
    depends_on:
      - db
    restart: on-failure
  db:
    image: "postgres:15"
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "SuperSecurePassword123!"
      POSTGRES_DB: "db"
